### ISSUE TITLE
Cannot initialize with a new repo

### ISSUE THREAD

**Issue by marcqualie** [marcqualie/diffcrypt#29]
The following errors have been observed on new Rails 6.0 applications with ruby 2.7.1

```ruby
# when file is empty
lib/diffcrypt/rails/encrypted_configuration.rb:102:in `decrypt': undefined method `decrypt_and_verify' for nil:NilClass (NoMethodError)
```

```ruby
# when file just contents `---`
lib/diffcrypt/file.rb:18:in `cipher': undefined method `[]' for nil:NilClass (NoMethodError)
```

```ruby
# when file contains non encrypted data, like `---\ntest: true`
lib/diffcrypt/encryptor.rb:37:in `decrypt_hash': undefined method `each' for nil:NilClass (NoMethodError)
```

**Comment by marcqualie** [comment]
Closed by #31
